[DATA-6476] 0.9.6.1 upgrade (#5)
* upgrading to 8.40 (#139)

* Option to add podAnnotations to jobs. (#137)

* feat(helm): add pod annotations to jobs

* feat(helm): add pod annotation to cron jobs.

* docs(helm): Add podAnnotation documentation and default values.

* feat(helm) chart version bump.

* update to v0.8.41 (#143)

* fix(mysql): update mysql helm chart version (#146)

* fix(metrics): fix Prometheus env variable in the MCE consumer deployment (#148)

* feat(datahub-frontend): Option to configure OIDC auth easily (#142)

* fix(kafka): update kafka chart version (#147)

* feat(datahub-frontend): Allow lifecycle hooks (#141)

* <feat>(datahub-frontend): Allow lifecycle hooks

This PR adds a lifecycle node to the datahub-frontend deployment template.
It can be used to execute lifecycle hooks, e.g. postStart actions, like
replacing the default user.props file.

* Bump chart version to 0.2.86

Co-authored-by: Pedro Silva <pedro.cls93@gmail.com>

* Update to v0.8.43 (#151)

* feat(upgrade): allow setting batch args (#155)

* feat(datahub-upgrade): Restore Indices Resources (#152)

* <feat>(datahub-upgrade): Restore Indices Resources

This PR adds the ability for end-users to specify resource requests and limits
for the datahub upgrade job 'restore indices'. This is needed for situations
where the restore indices job will OOM due to a large backfill of data. I've
seen this happening with our deployment of datahub and am unable to tune
the resources for the restore indices job because the current requests
and limits are hard-coded.

* fix(gms): remove unused JMX sidecar (#156)

* fix(gms): remove unused JMX sidecar
in favour of the already included JVM agent

* Update Chart.yaml

* Update Chart.yaml

* Bumping to v0.8.44 (#160)

* feat(ci): close stale issues/prs (#164)

* feat: add extra labels to ingress configurations (#163)

* feat(prerequisites): add postgresql to prerequistes Helm chart as an optional dependency (#121)

* feat(charts): add an option to configure revisionHistoryLimit to subcharts (#159)

* feat: datahub-frontend add oidc authentication client secret reference (#165)

* fix(monitoring) Fixes monitoring default values + gms chart version (#161)

* chore: bump datahub-actions version (#168)

* Feat(actions): Support mounting a customer defined k8s secrets as files needed in ingestion recipes (#169)

* Mount a customer defined k8s secret for ssl secrets needed in ingestion recipes

* Bump chart versions

* Address comment

* Update readme

* Address Pedro's comment

* feat(monitoring): enable monitoring on frontend (#171)

* Add kafka-exporter to expose prometheus metrics for kafka cluster (#170)

* Add kafka-exporter to expose prometheus metrics for kafka cluster

* Kafka-exporter: Updated values.yaml to support tls/sasl authentication while connecting kafka cluster

* Kafka-exporter: Updated values.yaml to remove default values and correct intendation

* Add kafka-exporter to expose prometheus metrics for kafka cluster

* Kafka-exporter: Updated values.yaml to support tls/sasl authentication while connecting kafka cluster

* Kafka-exporter: Updated values.yaml to remove default values and correct intendation

* Updated chart version

* Bumping actions (#173)

* feat(elasticsearch-setup): Add support for insecure curl connections (#166)

* fix versions, clean jmx exporter (#175)

* bumping helm charts for 0.8.45 (#178)

* bumping to 0.8.45

* Fixing

* feat(monitoring): Add optional ServiceMonitors to all JVM based services (#181)

* feat(frontend): add service monitoring

* feat(gms): add service monitoring

* gms: servicemonitor

* feat(mae): enable service monitoring

* update READMEs

* fix service ports

* bump version

* Add missing default value

* Update charts/datahub/Chart.yaml

* delete jmx config and rename port to http

* feat(secrets): Allow users to specify their own secret values at first boot (#180)

* fix(auth-secret): Make template use correct retrieval method

`datahub-auth-secret` yaml was incorrectly using the `index` template function which is for list variables. For dictionaries as is the case with the `$secret.data` object, the correct method is: https://helm.sh/docs/chart_template_guide/function_list/#get

Tested locally, that this works against a running cluster.

* Updates encryption secret to use get helm function

* feat(secrets): Allow users to specify their own secret values at first boot

* fix(datahub-frontend): Remove unused env var (#176)

* fix(datahub-frontend): Remove unused env var

* Bump chart version

* Change default versions 0.9.0 (#184)

* feat(release): automatically bumbp versions for all subcharts (#185)

* feat(release): automatically bumbp versions for all subcharts

* Remove kafka export as subchart
Kafka exporter is useful for monitoring datahub, but it's not part of it. It should be deploy sepratly, as we do in production

* Add script to bump versions together

* Add tagging to the workflow

* Don't run release on CI commits

* fix(CI): remove duplicate id (#189)

* fix(ci): us sh instead of bash; increase tag by patch (#190)

* DataHub Release v0.9.1  (#191)

* fix(v0.9.1): Fix v0.9.1 release versions (#192)

* Release v0.9.1 Helm

* Bump chart versions

* Fixing final 210

* release(v0.9.2) Release Helm Charts for DataHub v0.9.2 (#194)

* Bumping to release Helm charts for v0.9.2

* bump version by running:
 ./.github/scripts/bump-chart-versions.sh 0.2.112

Co-authored-by: szalai1 <szalaipeti.vagyok@gmail.com>

* fix(gha): revert auto bump release changes (#197)

* fix(datahub-upgrade): Add system auth credentials to datahub upgrade jobs (#199)

* fix(datahub-upgrade): Add system auth credentials to datahub upgrade jobs

* bump chart.yaml version

* feat(sql): extend sql username/password configuration (#198)

* Ebean credential configuration flexbility

Allows the EBEAN_DATASOURCE_USERNAME and EBEAN_DATASOURCE_PASSWORD to be specified either in global or in the gms config.
Also, allows a string value to be specified as the password to enable vault secret webhooks.

* Extended postgres creds config

* Extended mysql setup job creds config

* bump chart version

* bump chart version

* show example in values.yaml

* Added explanation to README

* fix typo

* tidy values.yaml examples

* consistent quote

Use the same quoting solution for sql password and usernames across the file

* remove space error

* Bump gms sub-chart

* Update Chart.yaml

* add nil condition to gms deploy

* ad nil conditional to mysql job

* add nil conditional to postgres job

* fix(frontend): increase recommended defaults (#202)

* docs: add secret key information (#195)

Added information about the key name in the secret, or it will fail like this:
Error: couldn't find key neo4j-password in Secret default/neo4j-secrets

* fix(doc): correct doc for serviceMonitor.create (#204)

* Bumping charts to v0.9.3 (#207)

* Update Chart.yaml (#208)

* doc Add global.elasticsearch.useSSL to values.yaml (#209)

* fix: only add DATAHUB_SYSTEM_CLIENT envs when metadata service auth enabled (#205)

Co-authored-by: Pedro Silva <pedro@acryl.io>

* fix(frontend): Correct lifecycle templating for frontend (#201)

* Fix lifecycle templating for frontend
Fixes `throws ValidationError(Deployment.spec.template.spec.containers[0].lifecycle): invalid type for io.k8s.api.core.v1.Lifecycle: got "string", expected "map"`

* bump up Chart.yaml version

* set default value for lifecycle

* Bump versions

Co-authored-by: Pedro Silva <pedro@acryl.io>

* fix(ingestion-cron): Make hostAliases work in datahub-ingestion-cron (#206)

* fix: make hostAliases work in datahub-ingestion-cron
* Bump ingestion cron subchart version

Fixes https://github.com/acryldata/datahub-helm/issues/200

Co-authored-by: Pedro Silva <pedro@acryl.io>

* bugfix: datahub-upgrade use datasource password value if set (#210)

* feat(global-version): add option to globally define versions (#212)

* Update versions & bitnami index (#219)

* Update prerequisite versions & bitnami repo

* fix: move default tag to global.datahub.version (#214)

image.tag in datahub-gms and datahub-fronted shadowed the
global.datahub.version from the top datahub chart, so the resulting
image was head.

* fix: move default tag to global in subcharts (#220)

* fix(jobs): Bump kafka setup resources + make all jobs resources configurable (#224)

* Remove release for master

* fix(jobs): Bump kafka setup resources + make all jobs resources configurable

* Add documentation

* Bump chart.yaml

* Lock upgrade job to v0.9.4

Co-authored-by: Dexter Lee <dexter@acryl.io>

* fix: add extra space before comment to make yamllint pass (#226)

* fix(release): Revert workflow change & change upgrade job to 0.9.3 (#227)

* feat(mce-consumer): removing dependency on gms for mce consumer (#216)

* feat(mce-consumer): removing dependency on gms for mce consumer envs

* feat(elasticsearch): adding elasticsearch index job (#228)

* Feat/elasticsearch optimization ext (#229)

* feat(elasticsearch): allow document count mismatch override

* Bumping the versions as part of v0.9.5 release (#230)

* Fix 232 (#233)

* fix(cron-ingestion): referecing $ values

* bump versions

* feat(elasticsearch):  build-indices job (#231)

* feat(elasticsearch): adding elasticsearch index job
* feat(elasticsearch): allow document count mismatch override
* Adjusting hook order build-indices job

* config(gms): enable elasticsearch reindex by default (#235)

* fix(jobs): Make job pull policy consistent with subchart (#237)

* fix(jobs): Make job pull policy consistent with subchart

* Explicitly set schema registry type

* Update charts/datahub/values.yaml

Co-authored-by: Peter Szalai  <szalaipeti.vagyok@gmail.com>

Co-authored-by: Peter Szalai  <szalaipeti.vagyok@gmail.com>

* fix(mce-consumer): Correct env vars & configure resources for all components (#238)

* fix(mce-consumer): Correct env vars & configure resources for all components

* Update quickstart values to use global datahub version

* Update elasticsearch memory configs

* fix(version) Update remaining values for 0.9.6 upgrade  (#239)

* v0.9.6.1 release (#241)

* Release bump fix (#243)

* fix(release version): fix missing global release bump to 0.9.6.1

* Update values.yaml (#244)

* Update values.yaml

* Update Chart.yaml

* fix(restore-indices): restore indices should use global datastore values (#247)

* expose oidc scope (#249)

* Update Chart.yaml (#251)

* fix(kafka-setup): Make kafka setup use explicit topic names (#245)

* fix(kafka-setup): Make kafka setup use explicit topic names

* Set kafka env vars for all deployments

* Update gms & actions pod env vars

* Add documentation for new properties

* Version bump (#250)

* bump versions

* GRAPH_SERVICE_DIFF_MODE_ENABLED false, it's important if we use neo4j

* graph_service_impl to elasticsearch

---------

Co-authored-by: Gabe Lyons <itsgabelyons@gmail.com>
Co-authored-by: Lukáš Novotný <42157644+novotl@users.noreply.github.com>
Co-authored-by: Aseem Bansal <asmbansal2@gmail.com>
Co-authored-by: RyanHolstien <RyanHolstien@users.noreply.github.com>
Co-authored-by: Justin Marozas <justinas.marozas@gmail.com>
Co-authored-by: Tomáš Kubín <tomas.kubin@blindspot.ai>
Co-authored-by: Toby Irmer <toby@irmer.com>
Co-authored-by: Pedro Silva <pedro.cls93@gmail.com>
Co-authored-by: Pedro Silva <pedro@acryl.io>
Co-authored-by: Hunter Elbourn <hunterelbourn@gmail.com>
Co-authored-by: Peter Szalai <szalaipeti.vagyok@gmail.com>
Co-authored-by: John Joyce <john@acryl.io>
Co-authored-by: Upendra Rao Vedullapalli <upendrao@gmail.com>
Co-authored-by: Felix Lüdin <13187726+Masterchen09@users.noreply.github.com>
Co-authored-by: Bumsoo Kim <bskim45@gmail.com>
Co-authored-by: Tony Ouyang <43738225+TonyOuyangGit@users.noreply.github.com>
Co-authored-by: Harshal Sheth <hsheth2@gmail.com>
Co-authored-by: Jinlin Yang <86577891+jinlintt@users.noreply.github.com>
Co-authored-by: Navin Sharma <103643430+NavinSharma13@users.noreply.github.com>
Co-authored-by: Bogdan Antoniu <bogdan.antoniu@gmail.com>
Co-authored-by: Callum Richard Edwards <34392823+CallumREdwards@users.noreply.github.com>
Co-authored-by: Álvaro González <alvaro.gonzalez@auctane.com>
Co-authored-by: David Haglund <548769+daha@users.noreply.github.com>
Co-authored-by: Andrea Scarpino <andrea@scarpino.dev>
Co-authored-by: Nurlan Farajov <nur.rico@gmail.com>
Co-authored-by: david-leifker <114954101+david-leifker@users.noreply.github.com>
Co-authored-by: Dexter Lee <dexter@acryl.io>
Co-authored-by: Adam Price <adam.price@afreshtechnologies.com>
Co-authored-by: Chris Collins <chriscollins3456@gmail.com>